# Generated by Django 5.2.13 on 2026-04-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payout',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='payout',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__isnull', False)), fields=('merchant', 'idempotency_key'), name='unique_active_idempotency_key'),
        ),
    ]
